export enum LocalizedNames {
    'ARABIC' = 'ar-AE',
    'GERMAN' = 'de-DE',
    'BRITISH' = 'en-GB',
    'ENGLISH' = 'en-US',
    'SPANISH' = 'es-ES',
    'MEXICAN' = 'es-MX',
    'FRENCH' = 'fr-FR',
    'INDONESIA' = 'id-ID',
    'ITALY' = 'it-IT', // 400 Unknown locale
    'JAPAN' = 'ja-JP',
    'KOREA' = 'ko-KR',
    'POLAND' = 'pl-PL',
    'BRAZIL' = 'pt-BR',
    'RUSSIA' = 'ru-RU',
    'THAILAND' = 'th-TH',
    'TURKEY' = 'tr-TR',
    'VIETNAM' = 'vi-VN',
    'CHINA' = 'zh-CN',
    'TAIWAN' = 'zh-TW',
}
